# Generated by Django 4.1.5 on 2023-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='abcd', max_length=100),
            preserve_default=False,
        ),
    ]
