# Generated by Django 4.1.5 on 2023-03-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='time',
        ),
    ]
