# Generated by Django 4.1.5 on 2023-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiserver', '0003_booking_additional_req_booking_booking_for_another_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_geo_ln',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
